name 'common_linux'
maintainer 'Jonathan Serafini'
maintainer_email 'jonathan@serafini.ca'
license 'apachev2'
description 'Installs/Configures chef_common_linux'
long_description 'Installs/Configures chef_common_linux'
version '0.1.0'

depends 'chef-client'
depends 'apt'
depends 'ubuntu'
depends 'ohai'
depends 'build-essential'
depends 'cron'
depends 'hostsfile'
depends 'ntp'
depends 'sysctl'
depends 'ulimit'
depends 'iptables'
depends 'rsyslog_ng'
