
syntax on
filetype on
filetype plugin on
filetype indent on

set nocompatible
set encoding=utf8

set backspace=eol,start,indent
set expandtab
set tabstop=2
set shiftwidth=2
set softtabstop=2
set autoindent

set hlsearch
set incsearch
set ignorecase
set smartcase
set showmatch
set number
set cursorline

set display=lastline

let g:is_bash=1

" return to last position on re-edit file
if has("autocmd")
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
        \| exe "normal g'\"" | endif
endif

